version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: aymanaloulou/devopsimagedocker:latest
    
    ports:
      - 8092:8092
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:




